### Hub Enterprise - chart data

# credentials for your image registry with HUB-ENTERPRISE images
imageCredentials:
  registry: "https://index.docker.io/v1"
  username: "username"
  password: "password"

# optional
postgres:
  # false if you manage DB yourself, outside this chart
  deploy: true
  image: postgres
  tag: "13"

dbData:
  OL_DB_PASSWORD: postgres
  OL_DB_USER: postgres
  OL_DB_HOST: hub-enterprise-postgres # DB accessed by pods
  OL_DB_NAME: postgres
  OL_DB_PORT: "5432"

keycloak:
  image: "openlegacy/openlegacy-keycloak:$KEYCLOAK_VERSION"
  hostname: "hub-enterprise-keycloak-he-demo-helm.apps.ol-cluster02.sdk-hub.com"
  ingress:
    type: openshift

dbMigration:
  image: "openlegacy/hub-enterprise-db-migration:3.0.1"

hubEnterprise:
  image: "openlegacy/hub-enterprise:3.0.1"
  hostname: "hub-enterprise-he-demo-helm.apps.ol-cluster02.sdk-hub.com"
  ingress:
    type: openshift
  storage:
    mountPath: "/ol-hub-tenant-artifacts"  # required for OpenShift

# !!! redirect URL for realm JSON should be set to: https://OL_HUB_URL/*
