services:
  postgres:
    image: $POSTGRES_REGISTRY_IMAGE_TAG
    container_name: "$OL_DB_NAME"
    restart: always
    networks:
      - hub-enterprise
    ports:
      - "$OL_DB_PORT:$OL_DB_PORT"
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=$POSTGRESQL_ADMIN_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ol-hub-db-data:/var/lib/postgresql/data
networks:
  hub-enterprise:
    external: true
volumes:
  ol-hub-db-data:
