version: '3.7'
services:
  loki:
    container_name: loki
    image: grafana/loki
    restart: always
    ports:
      - "3100:3100"
    networks:
      - hub-enterprise
    volumes:
      - loki-data:/loki

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - hub-enterprise
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - hub-enterprise

  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - ./grafana/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/loki.yaml:/etc/grafana/provisioning/datasources/loki.yaml
      - grafana-data:/var/lib/grafana
      - ./grafana/provider:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000/tcp
    networks:
      - hub-enterprise

networks:
  hub-enterprise:
    external: true

volumes:
  prometheus-data:
  loki-data:
  grafana-data:
