{
 "title": "Default",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "olTenantId",
    "label": "TenantId",
    "query": "4a6bfc5d-3bae-45a3-99b9-d1e255875adb"
   },
   {
    "name": "olProject",
    "label": "Project",
    "query": {
     "query": "label_values(system_cpu_count{tenantId=\"${olTenantId}\"}, project)"
    }
   },
   {
    "name": "step",
    "label": "Step",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Project: $olProject", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "olProject" },
  {
   "title": "Http Calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(http_server_requests_seconds_count{project=\"$olProject\",tenantId=\"$olTenantId\",uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\"}[$__range])) - (sum(http_server_requests_seconds_count{project=\"$olProject\",tenantId=\"$olTenantId\",uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\"}offset $__range) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(http_server_requests_seconds_count{project=\"$olProject\", uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\", tenantId=\"$olTenantId\", status!~\"2[0-9]{2}\"}[$__range])) by (status) - (sum(http_server_requests_seconds_count{project=\"$olPorject\", uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\", tenantId=\"$olTenantId\", status!~\"2[0-9]{2}\"} offset $__range) by (status) or (sum(max_over_time(http_server_requests_seconds_count{project=\"$olProject\", uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\", tenantId=\"$olTenantId\", status!~\"2[0-9]{2}\"}[$__range])) by (status) * 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{tenantId=\"$olTenantId\", project=\"$olProject\"})",
     "legendFormat": "Average CPU usage"
    }
   ]
  },
  {
   "title": "Total RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum by(environment) (jvm_memory_used_bytes{tenantId=\"$olTenantId\", project=\"$olProject\"}) / 1048576",
     "legendFormat": "All Instances Memory usage, MB"
    }
   ]
  },
  {
   "title": "Http Calls count per $step",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "(sum(max_over_time(http_server_requests_seconds_count{project=\"$olProject\", uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\", tenantId=\"$olTenantId\", status=~\"2[0-9]{2}\"}[$step])) - (sum(http_server_requests_seconds_count{project=\"$olProject\", uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\", tenantId=\"$olTenantId\", status=~\"2[0-9]{2}\"} offset $step) or (sum(max_over_time(http_server_requests_seconds_count{status=~\"2[0-9]{2}\"}[$step])) * 0))) or vector(0)",
     "legendFormat": "success"
    },
    {
     "expr": "((sum(max_over_time(http_server_requests_seconds_count{environment=\"$olEnvironment\", uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\", tenantId=\"$olTenantId\", status!~\"2[0-9]{2}\"}[$step])) - (sum(http_server_requests_seconds_count{environment=\"$olEnvironment\", uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\", tenantId=\"$olTenantId\", status!~\"2[0-9]{2}\"} offset $step) or (sum(max_over_time(http_server_requests_seconds_count{status!~\"2[0-9]{2}\"}[$step])) * 0))) > 0) or vector(0)",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Total RPC Calls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(ol_rpc_invoke_call_total{project=\"$olProject\",tenantId=\"$olTenantId\"}[$__range])) - (sum(ol_rpc_invoke_call_total{project=\"$olProject\",tenantId=\"$olTenantId\"}offset $__range) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success RPC Calls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(ol_rpc_invoke_succeed_total{project=\"$olProject\",tenantId=\"$olTenantId\"}[$__range])) - (sum(ol_rpc_invoke_succeed_total{project=\"$olProject\",tenantId=\"$olTenantId\"}offset $__range) or vector(0))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(max_over_time(ol_rpc_invoke_failed_total{project=\"$olProject\",tenantId=\"$olTenantId\"}[$__range])) - (sum(ol_rpc_invoke_failed_total{project=\"$olProject\",tenantId=\"$olTenantId\"}offset $__range) or vector(0))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Rpc Calls count per $step",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(max_over_time(ol_rpc_invoke_succeed_total{project=\"$olProject\", tenantId=\"$olTenantId\"}[$step])) by (status) - sum(ol_rpc_invoke_succeed_total{project=\"$olProject\", tenantId=\"$olTenantId\"} offset $step) by (status)",
     "legendFormat": "success"
    },
    {
     "expr": "sum(max_over_time(ol_rpc_invoke_failed_total{project=\"$olProject\", tenantId=\"$olTenantId\"}[$step])) by (status) - sum(ol_rpc_invoke_failed_total{project=\"$olProject\", tenantId=\"$olTenantId\"} offset $step) by (status)",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Http Calls rate per $step",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(max_over_time(http_server_requests_seconds_count{project=\"$olProject\", uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\", tenantId=\"$olTenantId\", status=~\"2[0-9]{2}\"}[$step])) by (status) - (sum(http_server_requests_seconds_count{project=\"$olProject\", uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\", tenantId=\"$olTenantId\", status=~\"2[0-9]{2}\"} offset $step) by (status) or (sum(max_over_time(http_server_requests_seconds_count{status=~\"2[0-9]{2}\"}[$step])) by (status) * 0))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(max_over_time(http_server_requests_seconds_count{environment=\"$olEnvironment\", uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\", tenantId=\"$olTenantId\", status!~\"2[0-9]{2}\"}[$step])) by (status) - (sum(http_server_requests_seconds_count{environment=\"$olEnvironment\", uri!~\"/actuator/health|/actuator/prometheus|/openapi/openapi.yaml|UNKNOWN|/actuator|/openapi\", tenantId=\"$olTenantId\", status!~\"2[0-9]{2}\"} offset $step) by (status) or (sum(max_over_time(http_server_requests_seconds_count{status!~\"2[0-9]{2}\"}[$step])) by (status) * 0))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Rpc Calls rate per $step",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "sum(max_over_time(ol_rpc_invoke_succeed_total{project=\"$olProject\", tenantId=\"$olTenantId\"}[$step])) by (status) - sum(ol_rpc_invoke_succeed_total{project=\"$olProject\", tenantId=\"$olTenantId\"} offset $step) by (status)",
     "legendFormat": "success"
    },
    {
     "expr": "sum(max_over_time(ol_rpc_invoke_failed_total{project=\"$olProject\", tenantId=\"$olTenantId\"}[$step])) by (status) - sum(ol_rpc_invoke_failed_total{project=\"$olProject\", tenantId=\"$olTenantId\"} offset $step) by (status)",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Log single view",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{project=\"$olProject\"}"
    }
   ]
  }
 ]
}