version: '3.7'
services:
  loki:
    container_name: loki
    image: $LOKI_REGISTRY_IMAGE:$LOKI_TAG
    restart: always
    ports:
      - "3100:3100"
    networks:
      - hub-enterprise
    volumes:
      - loki-data:/loki

  prometheus:
    container_name: prometheus
    image: $PROMETHEUS_REGISTRY_IMAGE:$PROMETHEUS_TAG
    ports:
      - "9090:9090"
    networks:
      - hub-enterprise
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  pushgateway:
    container_name: pushgateway
    image: $PUSHGATEWAY_REGISTRY_IMAGE:$PUSHGATEWAY_TAG
    ports:
      - "9091:9091"
    networks:
      - hub-enterprise

  grafana:
    image: $GRAFANA_REGISTRY_IMAGE:$GRAFANA_TAG
    restart: always
    volumes:
      - ./grafana/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/loki.yaml:/etc/grafana/provisioning/datasources/loki.yaml
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    networks:
      - hub-enterprise

networks:
  hub-enterprise:
    external: true

volumes:
  prometheus-data:
  loki-data:
  grafana-data:
